events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn_cache:10m max_size=1g inactive=60m use_temp_path=off;

    upstream sniplink_api {
        least_conn;
        server backend:3000;
    }

    server {
        listen 80;

        # 1. Attempt to serve static files (CSS, JS, index.html)
        location / {
            root /usr/share/nginx/html;
            index index.html;
            # If file doesn't exist, pass the request to the backend
            try_files $uri $uri/ @backend;
        }

        # 2. Define the backend fallback
        location @backend {
            proxy_pass http://sniplink_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Explicitly handle API requests to ensure they always hit the backend
        location /api/ {
            proxy_pass http://sniplink_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Cache API JSON responses
            proxy_cache cdn_cache;
            proxy_cache_valid 200 1m;
        }
    }
}