events {
    worker_connections 1024;
}

http {
    # 1. Define the CDN cache storage
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn_cache:10m max_size=1g inactive=60m use_temp_path=off;

    upstream sniplink_api {
        least_conn;
        server backend:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://sniplink_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # 2. Turn on the cache
            proxy_cache cdn_cache;
            
            # Cache successful redirects (like your short links) for 10 minutes
            proxy_cache_valid 301 302 10m; 
            
            # Cache API JSON responses for 1 minute
            proxy_cache_valid 200 1m;

            # 3. Add a header so you can see if the CDN worked
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}